### ISSUE TITLE
mailgun DNS setup instructions missing

### ISSUE THREAD

**Issue by mhaberler** [jimmyangel/rikitrakiws#4]
just working through them in routes/users.js

hm, mailgun seems a bit capricious

need to learn the node debugging business :-/

````
[2019-09-26 18:04:43.614] [INFO] [default] - add user {
  username: 'XXXX',
  email: 'XXXX@mah.priv.at',
  password: 'YYYYYYYYY',
  rturl: 'https://rikitraki.mah.priv.at/'
}
[2019-09-26 18:04:43.692] [INFO] http - ::ffff:46.125.249.125 - - "POST /api/v1/users HTTP/1.1" 201 21 "https://rikitraki.mah.priv.at/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36"
[2019-09-26 18:04:44.167] [ERROR] [default] - mailgun error { inspect: [Function: inspect] }
````

**Comment by jimmyangel** [comment]
I am assuming you opened your own mailgun account; they have detailed instructions on how to set up dns to enable mail send

**Comment by mhaberler** [comment]
yes

had to modify the API host thanks to EU GDPR insanity. That hurdle is taken.

Some token verification issue remains, got around it for a test by fudging the user entry in the databse.

**Comment by jimmyangel** [comment]
You mean mailgun token verification?

**Comment by mhaberler** [comment]
yes, the activate step fails when clicking through the registration confirmation mail

what's the canonical way to crank up logging ? export LOGLEVEL=DEBUG ?

**Comment by mhaberler** [comment]
that's the failed step:

````[2019-09-30 19:49:41.956] [ERROR] http - ::ffff:217.149.175.113 - - "GET /api/v1/token HTTP/1.1" 403 58 "https://rikitraki.mah.priv.at/activate.html?username=mhaberler&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyaWtpdHJha2kubWFoLnByaXYuYXQiLCJzdWIiOiJtaGFiZXJsZXIiLCJpYXQiOjE1Njk4NjU3NDd9._Xtfus2Lh6k5RvoLnY7wHdzH2LgExHUmOrr8kUGSitA" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36"````

jwt.io says "Invalid signature" for this token

**Comment by jimmyangel** [comment]
Hmmm, that would happen if the JWT_SECRET on rikitrakiws is different that the one that was set when you added the user. Is that possible? In jwt.io you would need to use the same secret as well.

**Comment by mhaberler** [comment]
I see - reading up and investigating. Warnedya - total JS idiot here ;)

**Comment by jimmyangel** [comment]
The JWT_SECRET is used by the service to sign JWT tokens that are sent to the user's browser once the user has logged in (the token is stored in localstorage, sort of like a cookie). When the user wants to do something that requires authentication (like upload a track), it uses the token to prove who they are, and the service trusts it because it signed the token. This is a nice way to handle user authentication without having to use sessions, which are really messy.

Same idea upon registration: the service sends a token to the user's email, which will then (on click) go to a page that calls the 'activate' service. Again, service trusts the token because it signed it.

If the secret changes, all tokens become invalid. In your hosting service you need a way to store this secret (and mailgun token too, another secret), and make sure the environment variable is set before starting the service. I am hosting in Google Compute Engine, which has a metadata storage service that can be used to store secrets.
